#!/bin/bash
set -e  # Stop bij fouten

# check if a specific file parameter is given
if [ -z "$1" ]; then
    # no parameter, process all XML files
    XML_FILES=(data/*.xml)
else
    # parameter given, process only that file in data directory
    FILE="data/$1.xml"
    if [ ! -f "$FILE" ]; then
        echo "File $FILE not found!"
        exit 1
    fi
    XML_FILES=("$FILE")
fi

# versies
SAXON_HE_VERSION="12.8"
XML_RESOLVER_VERSION="5.3.3"
XMLVALIDATOR_VERSION="1.0-SNAPSHOT"

# directories
SAXON_HE_HOME="library/saxon-he-${SAXON_HE_VERSION}"
XMLVALIDATOR_HOME="library/xmlvalidator-${XMLVALIDATOR_VERSION}"
OUT_DIR="_generated"

# jars
SAXON_HE_JAR="${SAXON_HE_HOME}/saxon-he-${SAXON_HE_VERSION}.jar"
XML_RESOLVER_JAR="${SAXON_HE_HOME}/xmlresolver-${XML_RESOLVER_VERSION}.jar"

# Maak output map
mkdir -p "$OUT_DIR"

# verwerk XML-bestanden
for f in data/*.xml; do
    echo "Processing $f..."
    # XML validatie (indien nodig, uitcommentariëren om te activeren)
    java -cp "$XMLVALIDATOR_HOME" be.bruggeman.cv.XmlValidator data/schema/tutorial.xsd "$f"

    # HTML generatie via XSLT
    java -cp "$SAXON_HE_JAR:$XML_RESOLVER_JAR" net.sf.saxon.Transform -s:"$f" -xsl:style/tutorial.xsl basedir="$OUT_DIR"
done

# kopieer assets
cp -r assets "$OUT_DIR/assets"

echo "Klaar."
